### ISSUE TITLE
Missing entry in pkg-list for mate settings ?

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-ports#11]
In ghostbsd-mate-settings repo under schemas there is 92_org.mate.NotificationDaemon.gschema.override but not in ghostbsd-mate-settings port pkg-list.
What we should do ? 
Need this to continue work for moving msd-background-helper from extra to mate settings.

**Comment by ericbsd** [comment]
use `make make-plist` and replace the list with the generated one.
