### ISSUE TITLE
x11/ghostbsd-slick-greeter-settings pkg-deinstall and pkg-install conflics with x11/lightdm

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-ports#12]
x11/ghostbsd-slick-greeter-settings/pkg-deinstall and x11/ghostbsd-slick-greeter-settings/pkg-install are is touching and lightdm config, ports configuring and other ports not allowed.

It is why that code is ghostbsd-build.

**Comment by angelescuo** [comment]
doesn't now

**Comment by ericbsd** [comment]
.conf is never upgraded only .conf.samples. If you knew how FreeBSD ports collection and packages work you would know that.

**Comment by angelescuo** [comment]
Indeed . conf.samples is upgraded. But what if conf.sample is upgraded from upstream ?
We remain with old .conf ? 
That's  what I have try to say.
Due to FreeBSD rules .conf files are not deleted at pkg delete  if are different from conf.sample.

**Comment by angelescuo** [comment]
So what's your idea/ideas to solve this ?

**Comment by ericbsd** [comment]
logindm.conf never changes from release to release. Noting to worry for now if it ever happens to make a quick patch it is easy to do, but I do not worry about this.
