### ISSUE TITLE
Minidlna the service is not create for openrc file

### ISSUE THREAD

**Issue by Tsuned-MX** [ghostbsd/ghostbsd-ports#31]
After installing minidlna file for openrc does not created

**Comment by Tsuned-MX** [comment]
rc-update: service `minidlna' does not exist

**Comment by vimanuelt** [comment]
Minidlna OpenRC files can be adapted from these OpenRC files, https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/minidlna/files

**Comment by ericbsd** [comment]
closing this since we moved to rc.d
