### ISSUE TITLE
legacy nvidia-driver-340 and -390 are missing in 12.2 and 13 ....

### ISSUE THREAD

**Issue by aschiebe** [ghostbsd/ghostbsd-ports#34]
Hi all,
on my two nvidia driven laptop I have searched for the legacy nvidia-driver-340 and -390 on version stable 12.2 and 13, both on latest updates. I have done a pkg seach nvidia and found only the current nvidia-driver-460 on both stable versions (12.2 and 13), but the old nvidia-libs are present.
I do only install with pkg install, no other source and package is on both on default as installed. On the 12.2 ghostbasd nvidia laptop I have installed sometime in the past -390 version, so in the past these driver version are present.
Please have a why they are missing.
Another curious thing is, if I look on nvidia drivers page for the right version for my graphic adapter, I got the info for freebsd x64 of a driver nvidia-driver-418 (NVIDIA-FreeBSD-x86_64-418.113 ), but this package is not present too.
I am not sure if this 418 version has something to do with the missing driver for 340, 390.
Please advice and have a look if there is something wrong in packages.
TanXs in advance and sorry If some info is missing, this is my first issue I create in github.
Please be patient with me, I am using ghostbsd for my main home laptop and I am really impressed by your work.
Ciao Arnold

**Comment by ericbsd** [comment]
Fixed ports I will start the build for those packages.

**Comment by ericbsd** [comment]
packages a syncing for 12 stable and 13 stable.
