### ISSUE TITLE
Upgrade to VLC 3.0.8_21,4 and it stop working

### ISSUE THREAD

**Issue by hanbosun** [ghostbsd/ghostbsd-ports#4]
Hi,
I recently installed GhostBSD 20.0.3 on VMPlayer (version: 15.5.1 build-15018445),  I found plenty issues. One is with the upgrade with VLC application.

I did the following to upgrade the VLC application to VLC 3.0.8_21,4. After the upgrade, VLC stopped working:

1. I had to upgrade my PKG application to version 1.14.2: command: sudo pkg upgrade -r GhostBSD pkg.
2. Then I run the following command to upgrade VLC: sudo pkg upgrade vlc
3. After the upgrade, I tried to start VLC from "Applications" -> "Sound & Video" -> "VLC", nothing happened.
4. I run VLC on the MATE terminal, and the following error message show:

`VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[0000000800933060] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e02)
Abort trap (core dumped)`

Not sure what else to do, I uninstalled VLC with command: sudo pkg remove vlc

Hope this helps with your trouble shooting.

**Comment by ericbsd** [comment]
To do upgrade with OS update you need to do a forced upgrade `pkg upgrade -f` or you will encounter errors like this. It is why we have an update manager that does the right thing.

**Comment by hanbosun** [comment]
When I first installed GhostBSD, I tried with the update manager. When it first run, it stuck in a infinite loop that was trying to upgrade pkg (which has 1.13.x), and yet it says pkg is at the most up to date version, That is problem #1 

It is why I had to do: sudo pkg upgrade -r GhostBSD pkg
to set the pkg to 1.14.x. This was a tip on google search page 1.

Then I run the update manager, it took a long time to download the packages, which is not an issue. As soon as it completed update libedit, the OS immediately get into error about libedit.so.x was not found. I did a restart and it stuck with libedit.so.x not found. This is issue #2.

I was going to open bugs on these 2 issues. I was not trying with the daily builds. Maybe these two got fixed with latest code changes?

**Comment by hanbosun** [comment]
BTW, GhostBSD is great, I installed on VMplayer 15, with only 2GB ram and 2.5 GB swap. runs super smooth, I can run it with my win 7 host at the same time with no slowdown. It recognized the Intel DRM video driver and sets the resolution correctly. Unlike the Linux distros I have tried, my god those ones slows to a crawl with only 4GB ram and the display resolution kept screwing up.

The only issues I am seeing are install packages, or updating some of them. Yet some of the install I have done seems to be very smooth, like GCC 9.3.0, OpenJDK 1.8, and Apache Maven. SSH and SFTP works out of the box. Great stuff! Keep up the good work.

**Comment by ericbsd** [comment]
Every time that you see os-generic-* in the list of upgrade you need to do a forced upgrade, as for the update manager loop it has been fixed and a repos configuration file was not removed in the release that caused packages issue installation and upgrades issue, I am about to release a new iso that will be at large a huge improvement from 20.03. Looks like or dev release are more stable than or releases itself.

**Comment by hanbosun** [comment]
Cool. Look forward to the new one. So far, I love the distro, It was sooo awesome. It was simple, stable, and fast. And all the functionalities I want were working great!
