### ISSUE TITLE
[Bug]: nvidia_xorg not working properly

### ISSUE THREAD

**Issue by x-shayan** [ghostbsd/ghostbsd-ports#47]
### NVIDIA Hybrid Graphics Driver

As far we know, GhostBSD now supports NVIDIA Optimus Drivers with x11/nvidia-hybrid-graphics and x11/nvidia-hybrid-graphics-390 ports. The port needs `nvidia_xorg` to work. 

When I type `sudo service nvidia_xorg onestart` it says: 
`kldload: an error occurred while loading module nvidia. Please check dmesg(8) for more details.`
` * ERROR: nvidia_xorg failed to start`

and end of dmesg says: 
`KLD nvidia.ko: depends on kernel - not available or version mismatch`
`linker_load_file: /boot/modules/nvidia.ko - unsupported file type`

that nvidia.ko is there in `nvidia-driver-390` package but If we want to install that, It has conflict with `nvidia-hybrid-graphics-390` 

I mean `nvidia-hybrid-grapics-390` needs nvidia.ko module but nvidia.ko module is in `nvidia-graphics-390` and they have conflicts. optimus will not work then 

### How to reproduce the bug?

I think this issue will solve If `nvidia-hybrid-graphics-390` adds nvidia.ko kernel module

### Expected behavior

Idk then.

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/ghostbsd-ports/pull/48

**Comment by ericbsd** [comment]
I will be closing that ticket soon since we are moving back to FreeBSD default init.

**Comment by ericbsd** [comment]
Now that we moved back to FreeBSD rc.d this ticket does not apply anymore.
